"""
Fresh, independent validation of the bootstrap particle filter used for the
out-of-sample predictive log-likelihood (src/evaluation/particle_filter.py).

Four checks:

  V1  Exact-likelihood check, base SV.  When phi = 0 the log-vol states h_t are
      i.i.d. N(mu, sigma^2), so the exact marginal log-likelihood is a sum of
      one-dimensional integrals p(r_t) = INT N(r_t; 0, e^h) N(h; mu, sigma^2) dh,
      computed to machine precision by Gauss-Hermite quadrature. The filter (an
      independent Monte Carlo method) must match it within its own MC error.
      Validates the Gaussian observation density and base propagation in absolute
      terms, not merely self-consistently.

  V2  Exact-likelihood check, SV-t.  Same phi = 0 construction with standardised
      Student-t errors, validating the t observation density / standardisation.

  V3  Leverage-convention check against stochvol::svsim (the benchmark simulator).
      Data generated by svsim with rho = -0.7 (forward convention); the filter
      profile log-likelihood over rho must peak at the CORRECT sign and magnitude.
      A backwards convention would peak at +0.7. This is the check that catches the
      historical contemporaneous-vs-forward bug.

  V4  Full parameter recovery, all four models.  On a long simulated series the
      profile log-likelihood along each parameter axis must be maximised at the
      true value (argmax within one grid step).

Run:  uv run python scripts/validate_particle_filter.py
"""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

import numpy as np
from numpy.polynomial.hermite import hermgauss
from scipy.special import logsumexp

from src.evaluation.particle_filter import sv_log_likelihood, _obs_log_density
from src.simulation.simulator import (
    simulate_sv, simulate_sv_leverage, simulate_sv_t, simulate_asv_t,
)
from src.simulation.sv_params import (
    SVParams, SVLeverageParams, SVtParams, ASVtParams,
)

PASS, FAIL = "PASS", "**FAIL**"


def _fixed(cls, **vals):
    """Config with each named parameter pinned to a single value (min == max)."""
    return cls(**{f"{k}_range": (v, v) for k, v in vals.items()})


def exact_loglik_phi0(r, mu, sigma, nu, n_nodes=200):
    """Exact log p(r_{1:T}) when phi = 0 (h_t i.i.d. N(mu, sigma^2)), via
    Gauss-Hermite quadrature over each observation."""
    x, w = hermgauss(n_nodes)                       # INT e^{-x^2} f(x) dx ~ sum w f(x)
    h = mu + np.sqrt(2.0) * sigma * x               # change of variables
    logw = np.log(w) - 0.5 * np.log(np.pi)
    return sum(logsumexp(logw + _obs_log_density(float(r_t), h, nu)) for r_t in r)


def filter_mean_se(r, seeds=range(8), **kw):
    vals = np.array([sv_log_likelihood(r, seed=s, **kw) for s in seeds])
    return vals.mean(), vals.std(ddof=1) / np.sqrt(len(vals))


def svsim(length, mu, phi, sigma, nu, rho, seed):
    """Generate a return path with stochvol::svsim (the benchmark simulator)."""
    out = tempfile.NamedTemporaryFile("w", suffix=".csv", delete=False).name
    nu_arg = "Inf" if not np.isfinite(nu) else str(nu)
    rscript = (
        f'suppressMessages(library(stochvol)); set.seed({seed}); '
        f's <- svsim(len={length}, mu={mu}, phi={phi}, sigma={sigma}, nu={nu_arg}, rho={rho}); '
        f'write.csv(data.frame(y=s$y), "{out}", row.names=FALSE)'
    )
    subprocess.run(["Rscript", "-e", rscript], check=True, capture_output=True, text=True)
    y = np.loadtxt(out, skiprows=1)
    Path(out).unlink(missing_ok=True)
    return y.astype(np.float64)


def profile(r, base, axis, grid, N=20000, seeds=range(4)):
    """Mean log-lik over `grid` values of parameter `axis`; return (argmax, lls)."""
    lls = np.array([
        np.mean([sv_log_likelihood(r, n_particles=N, seed=s, **{**base, axis: g})
                 for s in seeds])
        for g in grid
    ])
    return grid[int(np.argmax(lls))], lls


def main():
    results = []
    mu, sigma = -9.0, 0.30

    # ---- V1: base SV exact vs filter (phi = 0) ----
    print("V1  base SV: exact quadrature vs filter (phi=0)")
    r = simulate_sv(1, 1000, _fixed(SVParams, mu=mu, phi=0.0, sigma_eta=sigma), seed=1).returns[0].astype(np.float64)
    exact = exact_loglik_phi0(r, mu, sigma, np.inf)
    m, se = filter_mean_se(r, mu=mu, phi=0.0, sigma_eta=sigma, n_particles=100_000)
    ok = abs(m - exact) < 4 * se + 0.5
    print(f"    exact={exact:.3f}  filter={m:.3f}+/-{se:.3f}  |diff|={abs(m-exact):.3f}  -> {PASS if ok else FAIL}")
    results.append(("V1 base-SV exact likelihood", ok))

    # ---- V2: SV-t exact vs filter (phi = 0) ----
    print("V2  SV-t: exact quadrature vs filter (phi=0, nu=6)")
    nu = 6.0
    r = simulate_sv_t(1, 1000, _fixed(SVtParams, mu=mu, phi=0.0, sigma_eta=sigma, nu=nu), seed=2).returns[0].astype(np.float64)
    exact = exact_loglik_phi0(r, mu, sigma, nu)
    m, se = filter_mean_se(r, mu=mu, phi=0.0, sigma_eta=sigma, nu=nu, n_particles=100_000)
    ok = abs(m - exact) < 4 * se + 0.5
    print(f"    exact={exact:.3f}  filter={m:.3f}+/-{se:.3f}  |diff|={abs(m-exact):.3f}  -> {PASS if ok else FAIL}")
    results.append(("V2 SV-t exact likelihood", ok))

    # ---- V3: leverage convention vs svsim ----
    print("V3  leverage convention: svsim(rho=-0.7) -> filter profile over rho")
    mu3, phi3, sig3, rho3 = -9.0, 0.95, 0.25, -0.7
    y = svsim(4000, mu3, phi3, sig3, np.inf, rho3, seed=7)
    grid = np.round(np.arange(-0.9, 0.91, 0.1), 2)
    base = dict(mu=mu3, phi=phi3, sigma_eta=sig3, nu=np.inf)
    rhat, lls = profile(y, base, "rho", grid)
    ll_neg = lls[np.argmin(np.abs(grid + 0.7))]
    ll_pos = lls[np.argmin(np.abs(grid - 0.7))]
    ok = abs(rhat - rho3) <= 0.1 + 1e-9 and (ll_neg - ll_pos) > 20
    print(f"    argmax rho={rhat:+.2f} (true {rho3:+.2f})  LL(-0.7)-LL(+0.7)={ll_neg-ll_pos:+.1f}  -> {PASS if ok else FAIL}")
    results.append(("V3 leverage convention vs svsim", ok))

    # ---- V4: parameter recovery, all four models ----
    print("V4  parameter recovery (profile argmax at truth), all models")
    checks = []
    phg = np.round(np.arange(0.80, 0.996, 0.02), 3)
    sg  = np.round(np.arange(0.10, 0.45, 0.03), 3)
    ng  = np.array([4, 5, 6, 7, 8, 10, 15, 30], float)
    rg  = np.round(np.arange(-0.9, 0.01, 0.1), 2)

    # base SV: recover phi, sigma
    p = dict(mu=-9.0, phi=0.95, sigma_eta=0.25)
    r = simulate_sv(1, 4000, _fixed(SVParams, **p), seed=10).returns[0].astype(np.float64)
    base = dict(**p, nu=np.inf, rho=0.0)
    checks.append(("base phi",  profile(r, base, "phi", phg)[0], p["phi"], 0.02))
    checks.append(("base sigma", profile(r, base, "sigma_eta", sg)[0], p["sigma_eta"], 0.03))

    # SV-t: recover nu
    pt = dict(mu=-9.0, phi=0.95, sigma_eta=0.25, nu=6.0)
    r = simulate_sv_t(1, 6000, _fixed(SVtParams, **pt), seed=11).returns[0].astype(np.float64)
    base = dict(**pt, rho=0.0)
    checks.append(("SV-t nu", profile(r, base, "nu", ng)[0], pt["nu"], 2.0))

    # ASV: recover rho
    pl = dict(mu=-9.0, phi=0.95, sigma_eta=0.25, rho=-0.6)
    r = simulate_sv_leverage(1, 4000, _fixed(SVLeverageParams, **pl), seed=12).returns[0].astype(np.float64)
    base = dict(**pl, nu=np.inf)
    checks.append(("ASV rho", profile(r, base, "rho", rg)[0], pl["rho"], 0.1))

    # ASV-t: recover rho and nu
    pa = dict(mu=-9.0, phi=0.95, sigma_eta=0.25, rho=-0.6, nu=7.0)
    r = simulate_asv_t(1, 6000, _fixed(ASVtParams, **pa), seed=13).returns[0].astype(np.float64)
    base = dict(**pa)
    checks.append(("ASV-t rho", profile(r, base, "rho", rg)[0], pa["rho"], 0.1))
    checks.append(("ASV-t nu", profile(r, base, "nu", ng)[0], pa["nu"], 2.0))

    v4_ok = True
    for name, est, true, tol in checks:
        c = abs(est - true) <= tol + 1e-9
        v4_ok &= c
        print(f"    {name:12} argmax={est:>7} true={true:>6}  -> {PASS if c else FAIL}")
    results.append(("V4 parameter recovery", v4_ok))

    print("\n=== SUMMARY ===")
    all_ok = all(ok for _, ok in results)
    for name, ok in results:
        print(f"  {PASS if ok else FAIL}  {name}")
    print(f"\n{'ALL CHECKS PASSED' if all_ok else 'SOME CHECKS FAILED'}")
    return all_ok


if __name__ == "__main__":
    import sys
    sys.exit(0 if main() else 1)
