"""
Validation of the SV-t (standardised Student-t) particle filter.

The authoritative test of convention-match is to generate t-data with stochvol's
own svsim (verified to use standardised, unit-variance t-errors) and confirm our
filter's log-likelihood peaks at the true parameters — in particular at the true
nu. If our observation density disagreed with stochvol's, the nu profile would
peak at the wrong value.

Three checks:
  1. nu profile peaks near the true nu on stochvol-generated t-data.
  2. phi and sigma_eta profiles peak near truth on the same data.
  3. Normal-limit consistency: at large nu the t-density matches the Gaussian
     branch (same series, nu=500 vs nu=inf, log-likelihoods within noise).

The t-data is generated by an R subprocess (svsim) written to a temp CSV, then
read back into Python and passed to our filter.

Run:  uv run python scripts/validate_particle_filter_t.py
"""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

import numpy as np

from src.evaluation.particle_filter import sv_log_likelihood

R_TEMPLATE = """
suppressPackageStartupMessages(library(stochvol))
set.seed({seed})
sim <- svsim({T}, mu = {mu}, phi = {phi}, sigma = {sigma}, nu = {nu})
write.table(sim$y, file = "{out}", row.names = FALSE, col.names = FALSE)
"""


def simulate_svt(T, mu, phi, sigma, nu, seed):
    """Generate one SV-t series via stochvol's svsim (standardised t)."""
    with tempfile.NamedTemporaryFile("w", suffix=".csv", delete=False) as f:
        out = f.name
    script = R_TEMPLATE.format(seed=seed, T=T, mu=mu, phi=phi, sigma=sigma, nu=nu, out=out)
    subprocess.run(["Rscript", "-e", script], check=True, capture_output=True, text=True)
    y = np.loadtxt(out)
    Path(out).unlink()
    return y


def main():
    mu, phi, sigma, nu = -1.0, 0.95, 0.20, 6.0
    T = 2000
    print("=" * 66)
    print("SV-t FILTER VALIDATION (data from stochvol svsim, standardised t)")
    print(f"  true: mu={mu}, phi={phi}, sigma_eta={sigma}, nu={nu}, T={T}")
    print("-" * 66)

    r = simulate_svt(T, mu, phi, sigma, nu, seed=20)

    # Check 1: nu profile.
    nu_grid = [3, 4, 5, 6, 8, 12, 20, 40]
    ll = [sv_log_likelihood(r, mu, phi, sigma, nu=n, n_particles=20_000, seed=0)
          for n in nu_grid]
    nu_hat = nu_grid[int(np.argmax(ll))]
    print("  nu profile (mu, phi, sigma at truth):")
    for n, l in zip(nu_grid, ll):
        mark = "  <-- peak" if n == nu_hat else ""
        print(f"    nu={n:>3}: logL={l:10.3f}{mark}")
    print(f"  => nu peak at {nu_hat} (true {nu})")
    print()

    # Check 2: phi and sigma profiles at true nu.
    phi_grid = np.linspace(0.85, 0.99, 8)
    ll = [sv_log_likelihood(r, mu, p, sigma, nu=nu, n_particles=20_000, seed=0)
          for p in phi_grid]
    print(f"  phi peak at {phi_grid[int(np.argmax(ll))]:.3f} (true {phi})")

    sig_grid = np.linspace(0.05, 0.45, 9)
    ll = [sv_log_likelihood(r, mu, phi, s, nu=nu, n_particles=20_000, seed=0)
          for s in sig_grid]
    print(f"  sigma_eta peak at {sig_grid[int(np.argmax(ll))]:.3f} (true {sigma})")
    print()

    # Check 3: normal-limit consistency.
    print("  normal-limit check (same series, large nu vs Gaussian):")
    ll_big_nu = np.mean([sv_log_likelihood(r, mu, phi, sigma, nu=500,
                                           n_particles=20_000, seed=s) for s in range(5)])
    ll_gauss = np.mean([sv_log_likelihood(r, mu, phi, sigma, nu=np.inf,
                                          n_particles=20_000, seed=s) for s in range(5)])
    print(f"    logL(nu=500)={ll_big_nu:.3f}  logL(nu=inf)={ll_gauss:.3f}  "
          f"diff={abs(ll_big_nu - ll_gauss):.3f}")


if __name__ == "__main__":
    main()
